; WebRtcEndpoint.conf.ini

; [STUN Server 설정]
; Kurento가 자신의 공인 IP를 찾기 위해 물어볼 서버 주소. Coturn 서버를 바라보게함.
stunServerAddress=3.34.33.109
stunServerPort=3478

; [TURN Server 설정]
; P2P 연결이 불가능할 때 데이터를 중계해 줄 서버 주소.
; 형식: user:password@ip:port
turnURL=kurento:mcu_password@3.34.33.109:3478

; [Network 설정 - 핵심!]
; Docker NAT 안에 있는 Kurento에게 실제IP를 알려줌.
; 이 설정이 없으면 SDP에 사설 IP(172.x.x.x)가 들어가서 연결이 실패함.
externalAddress=3.34.33.109

; [선택 사항]
; 로컬 네트워크 인터페이스 이름 (Host Mode를 쓰므로 보통 eth0 또는 ens5)
; networkInterfaces=eth0